spring:
  datasource:
   primary:
     jdbc-url: jdbc:h2:mem:testdb1
     username: sa
     password: 
     driverClassName: org.h2.Driver
   secondary:
     jdbc-url: jdbc:h2:mem:testdb2
     username: sa
     password: 
     driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true